name: ndxn
favicon: null
layout_spectrum: 0.46140516828745604
typography_spectrum: 0.9572319693397731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9768716376274824
  lightness: 0.18754348205402493
  saturation: 0.44399236515164375
  rhythmicContrast: 0.10087984846904874
purpose: []
